name: push

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  BUF_VERSION: "1.10.0"
  BUF_PROTO_DIR: "proto"
  GO_VERSION: "1.18.1"

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      TG_BUILD_DATE: ${{ steps.info.outputs.TG_BUILD_DATE }}
      TG_VERSION: ${{ steps.info.outputs.TG_VERSION }}
      TG_REVISION: ${{ steps.info.outputs.TG_REVISION }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: export build info
        id: info
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          echo "TG_BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "TG_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "TG_REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo build date: ${{ steps.info.outputs.TG_BUILD_DATE }}
          echo version: ${{ steps.info.outputs.TG_VERSION }}
          echo revision: ${{ steps.info.outputs.TG_REVISION }}

  protobuf:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ env.BUF_VERSION }}
          github_token: ${{ github.token }}
      - name: lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: ${{ env.BUF_PROTO_DIR }}
      - name: check breaking
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: ${{ env.BUF_PROTO_DIR }}
          against: https://github.com/absurdlab/tigerd.git#branch=main,ref=HEAD~1,subdir=${{ env.BUF_PROTO_DIR }}
      - name: generate
        run: |
          buf generate
      - name: upload proto gen
        uses: actions/upload-artifact@v3
        with:
          name: proto_gen
          path: proto/gen

  build:
    runs-on: ubuntu-22.04
    needs:
      - prepare
      - protobuf
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: download proto gen
        uses: actions/download-artifact@v3
        with:
          name: proto_gen
          path: proto/gen
      - name: tidy
        run: |
          go mod tidy
      - name: unit tests
        run: |
          go test --tags unit ./...
      - name: integration tests
        run: |
          go test --tags integration ./...
